name: maharashtra_sports_app
description: "Maharashtra Sports Department - Mobile App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.7.0
  connectivity_plus: ^6.0.3

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
